### ISSUE TITLE
Update Guava to 24.1.1 or newer for CVE-2018-10237

### ISSUE THREAD

**Issue by efenderbosch** [launchdarkly/java-server-sdk#158]
https://nvd.nist.gov/vuln/detail/CVE-2018-10237

We are using OWASP's CVE checker and all versions of the client are flagged since they use Guava lower than 24.1.1.

We can suppress the CVE, but it would be nice to not need to do so.

**Comment by bwoskow-ld** [comment]
Hi efenderbosch,

Thanks for letting us know. We'll get this into the next version of the Java client.

**Comment by bwoskow-ld** [comment]
Hi efenderbosch,

After looking into this a bit more, it appears that we're not ready to bump to Guava 24.1.1 or later. The LD java-client still supports Java 7+ and Guava 21+ requires Java 8+. As a result we can only upgrade as far as Guava 20.x while supporting Java 7 and won't pick up the security fix. I'll raise some internal conversations around Java 7 support but that will take longer than expressed in my initial message.

In the meantime I recommend you take one of two steps:

1. You suppress the CVE if you're comfortable doing so.
2. You switch to using the thin distribution of LD's java-client ([details](https://github.com/launchdarkly/java-client#distributions)) and then add a sufficiently new version of the Guava dependency on your own. Note that you may need to add other dependencies which are in the default jar but not the thin jar.

**Comment by Ancient123** [comment]
I mean, Java 7 got end-of-lifed in 2015. It probably isn't worth keeping vulnerable dependancies to support out-of-support versions of the JVM.

**Comment by eli-darkly** [comment]
Well, as @bwoskow-ld mentioned, there is an ongoing internal discussion about when to drop Java 7 support. When you have a large customer base, it sometimes happens that there are large organizations who are still using very old versions of things and so it can be necessary to support them, even if that's not the decision you would make when building a new product. As I'm sure you can imagine, we would very much prefer to be able to work in Java 8+.

And since (as he also mentioned, in point 2) there is a straightforward workaround to eliminate the vulnerability, our decision about Java 7 support can't be solely driven by this concern.

**Comment by Ancient123** [comment]
Hey guys, happy new year!

Any progress on having those discussions about updating guava?

**Comment by eli-darkly** [comment]
@Ancient123 Yes, there is progress, but we have not yet reached a decision about dropping Java 7 support. I realize that this may seem silly to people who already dropped Java 7 long ago, but the reasons I stated are still the same, and again, there is a simple workaround.

**Comment by Ancient123** [comment]
Just continuing to express my interest as a customer.

**Comment by eli-darkly** [comment]
Absolutely. I just wanted to clarify that it's not exactly a discussion about whether to update Guava, it's a discussion about dropping Java 7 support.

**Comment by eli-darkly** [comment]
We've updated our [End of Life Policy](https://launchdarkly.com/policies/end-of-life-policy/), specifically the section that starts "Additionally, the SDKs and Relay Proxy may drop compatibility with versions of their underlying platforms which are no longer actively supported or being developed by their respective maintainers". The upshot of this is that starting on February 29th 2020, new releases of the LaunchDarkly Java SDK will no longer support Java 7. At that point we'll also update Guava.

Java 8 is pretty far out of date at this point too, but it is still a long-term support version so we are not dropping it yet.

**Comment by eli-darkly** [comment]
My previous comment was slightly wrong since we did do another minor version release that retained Java 7 support, but we are getting close to releasing version 5.0.0 which will drop it and will also introduce a lot of other (hopefully) desirable changes. A 5.0.0-rc1 beta will be out this week and the full release will follow soon.

**Comment by eli-darkly** [comment]
OK, for anyone who is curious, the [beta release](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.0.0-rc1)— which includes the Guava update as well as many other improvements— is out now, and we are hoping to release the real 5.0.0 within a couple of weeks.

**Comment by eli-darkly** [comment]
The 5.0.0 release is finally out; sorry for the extra delay.
