### ISSUE TITLE
Jar shading issue with NewRelic integration in NewRelicReflector

### ISSUE THREAD

**Issue by apottere** [launchdarkly/java-server-sdk#171]
**Describe the bug**
NewRelicReflector never works, because it's looking for the location of the `NewRelic` jar in the wrong package: `com.launchdarkly.shaded.com.newrelic.api.agent.NewRelic`

**To reproduce**
https://github.com/apottere/launchdarkly-newrelic-bug/tree/master

```
mvn exec:java -Dexec.mainClass="com.launchdarkly.client.DemoApplication"
```

**Expected behavior**
When running that application, I would expect to see this logged:
```
Used actual package: com.newrelic.api.agent.NewRelic
```

Instead, I see this logged:
```
Used shaded package: com.launchdarkly.shaded.com.newrelic.api.agent.NewRelic
```

**SDK version**
4.8.0

**Language version, developer tools**
Java 8

**OS/platform**
MacOS

**Comment by eli-darkly** [comment]
Thanks for pointing this out. Either due to having changed which shading plugin we were using, or due to a change in the behavior of that plugin at some point, it started not just shading the classes in the jar but also transforming the string parameter in a call to `Class.forName()`. It's a bit odd for it to do so for a class name that is clearly not one of the classes being shaded— I would think that that would make the tool's default behavior unusable for code that had to check for the presence of any external framework at all— but it should be possible to override this.

**Comment by apottere** [comment]
Yeah, I was surprised to see that was getting shaded as well - hopefully it's an easy fix in the shader config.  Thanks for taking a look!

**Comment by eli-darkly** [comment]
Please let us know once you've had a chance to retest with the 4.8.1 release.

**Comment by apottere** [comment]
@eli-darkly that fixed it, thank you!

**Comment by eli-darkly** [comment]
Annoyingly, this was _not_ an easy fix in the Shadow plugin config. We're still trying to figure out why it behaves this way; in the meantime, we've implemented a workaround in the code that is pretty silly-looking, but does work.

**Comment by apottere** [comment]
Haha yeah, I was looking at the workaround yesterday.  If its silly and it works, ¯\_(ツ)_/¯
