### ISSUE TITLE
Differentiate between recoverable and non recoverable connections Problems

### ISSUE THREAD

**Issue by andimarek** [launchdarkly/java-server-sdk#190]
**Is your feature request related to a problem? Please describe.**
Currently [StreamProcessor](https://github.com/launchdarkly/java-server-sdk/blob/master/src/main/java/com/launchdarkly/client/StreamProcessor.java#L109) logs all connection problems as Error, even if it is a recoverable one that will result in a retry. 

**Describe the solution you'd like**
It would be great to differentiate between the different connection errors and log only the non recoverable ones as ERROR.

Would you be open to a PR that changes that behavior? 

**Additional context**
This is the problem space as https://github.com/launchdarkly/java-server-sdk/pull/183.

**Comment by eli-darkly** [comment]
The reason we haven't acted on #183 yet is that there's not a clear consensus on how people would prefer for the logging behavior to work. The reporter of that issue seems to want the opposite behavior of what you want: that is, they want _more_ errors to be logged at ERROR level even though they are transient. Basically, people have different interpretations of what should count as ERROR based on how they prefer to do monitoring/ops.

In the case of the stream connection, the only errors that it will never try are HTTP error statuses from the server that indicate that the SDK is either misconfigured (401/403 - an invalid SDK key will never become valid) or very broken (405 - if we're trying to do a POST to a GET endpoint then it's probably a mistake by the SDK). Those are rare. _All_ other errors are potentially recoverable, usually representing either a network outage or a transient server-side problem, so they will be retried.

On a practical level we understand that this is inherently frustrating because you don't want to get monitoring alerts about a transient problem, but it has no way to know _at that time_ how transient it will or won't be. So one possible approach we've considered is to keep track of how long a period of consecutive errors has been going on, and escalate the log level if it continues failing for X amount of time.

**Comment by eli-darkly** [comment]
Update: as I suggested at the end of the last comment, what we are planning to do for the 5.0.0 release (although it didn't make it into the 5.0.0-rc1 beta) is as follows:

* All _recoverable_ errors (that is, any kind of network error, and any kind of HTTP error status that _doesn't_ mean you have an invalid SDK key and should give up) will be logged at `WARN` level. That includes stream errors, polling request errors, and failed event posts.
* There will be a configurable time threshold which, if the stream (or polling) has been failing continuously for that amount of time, will cause the SDK to log a single message at `ERROR` level. The message will say that updates have been unavailable for X amount of time, and will briefly describe why (network errors, HTTP 503 errors, etc. - any further details would have already been logged in earlier `WARN` messages). If it then gets a valid connection, it will emit a `WARN` message saying that the previous outage has been resolved, and then it will reset its state so that if there is another outage it repeats all of the above.
* All _unrecoverable_ errors (like invalid SDK key), which by definition can only happen once during the SDK's lifetime, will be logged at `ERROR`.

**Comment by eli-darkly** [comment]
Actually, all of the above did make it into the [5.0.0-rc1](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.0.0-rc1) beta release, in case you want to check that out in advance of the full release. And there is additional functionality in [5.0.0-rc2](https://github.com/launchdarkly/java-server-sdk/releases/tag/5.0.0-rc2) that lets your code subscribe to notifications about any such errors.

**Comment by eli-darkly** [comment]
The 5.0.0 release is out now, which includes the changes described above. It also adds some new features that might be useful if you want to query the connection status programmatically, rather than just monitoring the log output; see [DataSourceStatusProvider](https://javadoc.io/doc/com.launchdarkly/launchdarkly-java-server-sdk/latest/com/launchdarkly/sdk/server/interfaces/DataSourceStatusProvider.html).
