### ISSUE TITLE
LDClient is failed to initialised with below mentioned error

### ISSUE THREAD

**Issue by aradesai** [launchdarkly/java-server-sdk#218]
LDClient is failed to initialised with below mentioned error, not sure what is missing here, as the error is not really helpful here, this is a blocker for us.

**Is this a support request?**
This issue tracker is maintained by LaunchDarkly SDK developers and is intended for feedback on the SDK code. If you're not sure whether the problem you are having is specifically related to the SDK, or to the LaunchDarkly service overall, it may be more appropriate to contact the LaunchDarkly support team; they can help to investigate the problem and will consult the SDK team if necessary. You can submit a support request by going [here](https://support.launchdarkly.com/) and clicking "submit a request", or by emailing support@launchdarkly.com.

Note that issues filed on this issue tracker are publicly accessible. Do not provide any private account information on your issues. If your problem is specific to your account, you should submit a support request as described above.

**Describe the bug**

**To reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Logs**
`20/11/10 16:38:14 INFO FeatureFlagProvider: Revert all boolean flags [false], Revert specific boolean flags [null]
20/11/10 16:38:14 INFO LDClient: Enabling streaming API
20/11/10 16:38:14 INFO EventSource: Starting EventSource client using URI: https://stream.launchdarkly.com/all
20/11/10 16:38:14 INFO LDClient: Waiting up to 5000 milliseconds for LaunchDarkly client to start...
20/11/10 16:38:15 INFO EventSource: Connected to Event Source stream.
20/11/10 16:38:15 ERROR StreamProcessor: LaunchDarkly service request failed or received invalid data: com.launchdarkly.client.StreamProcessor$StreamInputException: com.launchdarkly.client.interfaces.SerializationException: java.lang.RuntimeException: Failed to invoke public com.launchdarkly.client.value.LDValue() with no args
20/11/10 16:38:15 INFO EventSource: Waiting 1286 milliseconds before reconnecting...
20/11/10 16:38:16 INFO EventSource: Connected to Event Source stream.
20/11/10 16:38:16 ERROR StreamProcessor: LaunchDarkly service request failed or received invalid data: com.launchdarkly.client.StreamProcessor$StreamInputException: com.launchdarkly.client.interfaces.SerializationException: java.lang.RuntimeException: Failed to invoke public com.launchdarkly.client.value.LDValue() with no args
20/11/10 16:38:16 INFO EventSource: Waiting 3095 milliseconds before reconnecting...
20/11/10 16:38:19 ERROR LDClient: Timeout encountered waiting for LaunchDarkly client initialization
20/11/10 16:38:19 WARN LDClient: LaunchDarkly client was not successfully initialized`

**SDK version**
4.14.0

**Language version, developer tools**
Java 8

**OS/platform**
Ubuntu 16.04

**Additional context**

**Comment by eli-darkly** [comment]
First: please fill in the fields of the bug report form, instead of just copying the instructions here. In particular: please tell us the version of this SDK that you are using, the language version, and the OS platform.

**Comment by eli-darkly** [comment]
Second: this isn't an error we've seen before. It looks like a problem with JSON deserialization, _possibly_ having something to do with an incompatible version of Gson, but without knowing what version of the SDK you're using (or anything else other than the logs you provided) it's impossible to say more. It might be helpful to know the rest of the dependencies in your project— at least for open-source things like Gson, if any.

**Comment by aradesai** [comment]
Updated the details accordingly

**Comment by eli-darkly** [comment]
Another thing that the bug report form asks for is "steps to reproduce". At a minimum, we would need to know whether this is something that happens consistently— like, if we ran your code right now, would we expect it to happen— or if it's something you only saw once, and if so, when (the timestamps in the log are not adequate because we don't know what your time zone is) in case it is correlated with any service-side issue.

**Comment by aradesai** [comment]
Yes we are hitting this issue consistently. 
Steps to reproduce is quite straight forward, while trying to connect to LD for Feature Flag from a Big Data app, i am hitting the issue.
GSON version: com.google.code.gson:gson:jar:2.8.0

**Comment by eli-darkly** [comment]
If this happens every time, could you please try setting your minimum log level to DEBUG and starting up again, to see if there is any stacktrace information in the debug-level logging from the SDK?

Also, could you show your project's LaunchDarkly SDK dependency as well? I know you said the version is 4.14.0, but there are still several different ways to reference the same release version (such as the "thin" or "all" classifiers).

The specific exception you're seeing is what would happen if Gson did not know to use the custom Gson deserializer that the SDK defines for the LdValue class. This normally happens automatically due to [the `@JsonAdapter` annotation](https://github.com/launchdarkly/java-server-sdk/blob/4.14.4/src/main/java/com/launchdarkly/client/value/LDValue.java#L30) on the class, which is a standard Gson feature; when that is present, Gson should not be trying to call the LDValue constructor. I'm not sure how to account for this behavior unless either 1. there are somehow two different versions of Gson on the classpath or 2. some other kind of issue with the application's packaging (such as shading dependencies) has changed the names of classes.

**Comment by aradesai** [comment]
As you rightly pointed out its GSON and Guava jar issue and i rectified by putting the correct version.
