### ISSUE TITLE
launchdarkly-java-server-sdk 5.2.2 jar is not in maven central

### ISSUE THREAD

**Issue by chenrui333** [launchdarkly/java-server-sdk#223]
👋  looks like the jar is not in the maven central yet, just FYI.

![image](https://user-images.githubusercontent.com/1580956/104794656-fd28d080-5776-11eb-8b59-c27e9c9d3bd9.png)

**Comment by bwoskow-ld** [comment]
Hi @chenrui333,

Maven Central has had some incidents over the past day plus which introduced a lot of service latency. [Here](https://status.maven.org/incidents/3zl7lx5p4rq4) is today's incident which elongated today's SDK release process.

I verified that 5.2.2 _is_ in Maven Central per https://repo1.maven.org/maven2/com/launchdarkly/launchdarkly-java-server-sdk/5.2.2/ even if the [Maven Repository site](https://mvnrepository.com/artifact/com.launchdarkly/launchdarkly-java-server-sdk) says otherwise. I verified as much in a local build. Hopefully Maven Repository will catch up soon and Maven Central's issues will be behind them. I'll leave this ticket open until 5.2.2 shows up on the linked page.

Cheers,
@bwoskow-ld

**Comment by chenrui333** [comment]
@bwoskow-ld that totally makes sense, thanks!! :)

**Comment by bwoskow-ld** [comment]
It looks like the 5.2.2 version propagated out to Maven Central's mirrors and ancillary services some time over the past few days. I'm going to go ahead and close this issue.

**Comment by chenrui333** [comment]
Thank you! Gonna retry on my end. :)
